# This is a basic workflow to help you get started with Actions

name: ABAP Unit Tests

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SAP CLI
        uses: amannn/sap-nwrfc-action@v1.1
        with: 
          sap-nwrfc-exe: ${{ secrets.SAP_NWRFC_EXE }}
          sap-nwrfc-lib: ${{ secrets.SAP_NWRFC_LIB }}

      - name: Run ABAP Unit Tests
        run: |
          abaplint --exclude=node_modules '**/*.abap'

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
