name: Демо CI для АБАПа
run-name: ${{ github.actor }} проверяет АБАП 🚀
on: [push]
jobs:
  Simulate_ABAP_CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Задача запущена по событию ${{ github.event_name }}."
      - run: echo "🐧 Задача работает на ${{ runner.os }} сервере GitHub-а!"
      - run: echo "🔎 Название ветки ${{ github.ref }} и ваш репозиторий ${{ github.repository }}."
      - name: Загружаем код репозитория
        uses: actions/checkout@v6
      - run: echo "💡 Код репозитория ${{ github.repository }} был клонирован на runner."
      - run: echo "🖥️ Workflow готов к тестированию вашего кода на runner."
      - name: Список файлов в репозитории
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
